// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransactionsService.Repositories;

#nullable disable

namespace TransactionsService.Migrations
{
    [DbContext(typeof(TransactionsServiceDbContext))]
    [Migration("20250526202736_TranFix")]
    partial class TranFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("transactions")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransactionsService.Models.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Image")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Merchant")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Transactions", "transactions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountId = 1L,
                            CategoryId = 3L,
                            CreationDate = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "First transaction",
                            TransactionDate = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 0,
                            UserId = 1L,
                            Value = 400m
                        },
                        new
                        {
                            Id = 2L,
                            AccountId = 2L,
                            CategoryId = 4L,
                            CreationDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 0,
                            Description = "Test transaction 2",
                            Merchant = "Local Store",
                            Title = "Something for home",
                            TransactionDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 1,
                            UserId = 1L,
                            Value = -200m
                        },
                        new
                        {
                            Id = 3L,
                            AccountId = 2L,
                            CategoryId = 6L,
                            CreationDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 0,
                            Description = "Test transaction 2",
                            Merchant = "Local Store",
                            Title = "Cheeeeese",
                            TransactionDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 1,
                            UserId = 1L,
                            Value = -400m
                        },
                        new
                        {
                            Id = 4L,
                            AccountId = 2L,
                            CategoryId = 5L,
                            CreationDate = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 2",
                            Merchant = "Local Store",
                            Title = "Coins from fountain",
                            TransactionDate = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 0,
                            UserId = 1L,
                            Value = 100m
                        },
                        new
                        {
                            Id = 5L,
                            AccountId = 5L,
                            CategoryId = 3L,
                            CreationDate = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "Some Income",
                            TransactionDate = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 0,
                            UserId = 1L,
                            Value = 100m
                        },
                        new
                        {
                            Id = 6L,
                            AccountId = 1L,
                            CategoryId = 3L,
                            CreationDate = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "Finally Salary",
                            TransactionDate = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 0,
                            UserId = 1L,
                            Value = 1100m
                        },
                        new
                        {
                            Id = 7L,
                            AccountId = 4L,
                            CategoryId = 9L,
                            CreationDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "New Tshirt",
                            TransactionDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 1,
                            UserId = 1L,
                            Value = -200m
                        },
                        new
                        {
                            Id = 8L,
                            AccountId = 3L,
                            CategoryId = 10L,
                            CreationDate = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "Movie tickets",
                            TransactionDate = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 1,
                            UserId = 1L,
                            Value = -400m
                        },
                        new
                        {
                            Id = 9L,
                            AccountId = 6L,
                            CategoryId = 8L,
                            CreationDate = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 0,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "Parents help",
                            TransactionDate = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 0,
                            UserId = 1L,
                            Value = 600m
                        },
                        new
                        {
                            Id = 10L,
                            AccountId = 2L,
                            CategoryId = 11L,
                            CreationDate = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "Food from market",
                            TransactionDate = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 1,
                            UserId = 1L,
                            Value = -100m
                        },
                        new
                        {
                            Id = 11L,
                            AccountId = 1L,
                            CategoryId = 6L,
                            CreationDate = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "Cafe breakfast",
                            TransactionDate = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 1,
                            UserId = 1L,
                            Value = -200m
                        },
                        new
                        {
                            Id = 12L,
                            AccountId = 5L,
                            CategoryId = 5L,
                            CreationDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "Some money for helping",
                            TransactionDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 0,
                            UserId = 1L,
                            Value = 200m
                        },
                        new
                        {
                            Id = 13L,
                            AccountId = 1L,
                            CategoryId = 4L,
                            CreationDate = new DateTime(2025, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "Some new dishes",
                            TransactionDate = new DateTime(2025, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 1,
                            UserId = 1L,
                            Value = -300m
                        },
                        new
                        {
                            Id = 14L,
                            AccountId = 4L,
                            CategoryId = 3L,
                            CreationDate = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "Salary again",
                            TransactionDate = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 0,
                            UserId = 1L,
                            Value = 1100m
                        },
                        new
                        {
                            Id = 15L,
                            AccountId = 4L,
                            CategoryId = 12L,
                            CreationDate = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "Flat rent",
                            TransactionDate = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 1,
                            UserId = 1L,
                            Value = -1000m
                        },
                        new
                        {
                            Id = 16L,
                            AccountId = 3L,
                            CategoryId = 6L,
                            CreationDate = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            Description = "Test transaction 1",
                            Merchant = "Amazon",
                            Title = "Another day, another cafe",
                            TransactionDate = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 1,
                            UserId = 1L,
                            Value = -300m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
