// <auto-generated />
using CaregoryAccountService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CategoryAccountService.Migrations
{
    [DbContext(typeof(CategoryAccountServiceDbContext))]
    [Migration("20250326174153_EnhancedDataset")]
    partial class EnhancedDataset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("category_accounts")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaregoryAccountService.Models.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("TransactionsCount")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Accounts", "category_accounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountName = "Bank",
                            AccountType = 0,
                            Balance = 1500,
                            Color = "#b14242",
                            Currency = 1,
                            Description = "Primary checking account",
                            TransactionsCount = 0,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            AccountName = "Cash",
                            AccountType = 1,
                            Balance = 5000,
                            Color = "#33cf5a",
                            Currency = 0,
                            Description = "Long-term savings account",
                            TransactionsCount = 0,
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("CaregoryAccountService.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CategoryType")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Categories", "category_accounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Transfer",
                            CategoryType = 2,
                            Icon = "/assets/exchange-arrows.png"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Correction",
                            CategoryType = 3,
                            Icon = "/assets/increase.png"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Salary",
                            CategoryType = 0,
                            Icon = "/assets/categories/bills.png"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Shopping",
                            CategoryType = 1,
                            Icon = "/assets/categories/shopping.png"
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Random money",
                            CategoryType = 0,
                            Icon = "/assets/categories/wallet.png"
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Food",
                            CategoryType = 1,
                            Icon = "/assets/categories/curry.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
