// <auto-generated />
using System;
using System.Collections.Generic;
using BudgetingService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetingService.Migrations
{
    [DbContext(typeof(BudgetingServiceDbContext))]
    [Migration("20250502163517_MoreInitialData")]
    partial class MoreInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("budgets")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetingService.Models.Budget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<List<long>>("AccountIds")
                        .HasColumnType("bigint[]");

                    b.Property<string>("BudgetName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("BudgetStatus")
                        .HasColumnType("integer");

                    b.Property<int>("BudgetType")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<long>>("CategoryIds")
                        .HasColumnType("bigint[]");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("CurrValue")
                        .HasColumnType("numeric");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("numeric");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("WarningShowed")
                        .HasColumnType("boolean");

                    b.Property<int>("WarningThreshold")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Budgets", "budgets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountIds = new List<long> { 1L },
                            BudgetName = "Monthly Groceries",
                            BudgetStatus = 0,
                            BudgetType = 1,
                            CategoryIds = new List<long> { 4L, 6L },
                            Color = "#3f3dbf",
                            CurrValue = 100m,
                            Currency = 1,
                            Description = "Budget for monthly grocery shopping",
                            PeriodEnd = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            PeriodStart = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PlannedAmount = 500m,
                            UserId = 1L,
                            WarningShowed = false,
                            WarningThreshold = 80
                        },
                        new
                        {
                            Id = 2L,
                            AccountIds = new List<long> { 2L, 4L },
                            BudgetName = "Vacation Savings",
                            BudgetStatus = 0,
                            BudgetType = 0,
                            CategoryIds = new List<long> { 3L, 5L },
                            Color = "#34bbb7",
                            CurrValue = 200m,
                            Currency = 0,
                            Description = "Saving up for a summer vacation",
                            PeriodEnd = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            PeriodStart = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PlannedAmount = 2000m,
                            UserId = 2L,
                            WarningShowed = false,
                            WarningThreshold = 90
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
